server:
  port: 8883

spring:
  application:
    name: food-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${elm.db.host}:3306/elm_food
    username: ${elm.db.username}
    password: ${elm.db.pw}
    hikari: # 配置连接池读已提交
      transaction-isolation: TRANSACTION_READ_COMMITTED

  data:
    redis:
      host: ${elm.data.redis.host}
      port: 6379
      password: ${elm.data.redis.password}
      database: ${elm.data.redis.database}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms


mybatis:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
  # 指定XML映射文件位置
  mapper-locations:
    - classpath*:com/tju/elm/food/mapper/*.xml


# swagger
springdoc:
  api-docs:
    enabled: true
    path: /food/v3/api-docs
  swagger-ui:
    enabled: true
    path: /food/swagger-ui

logging:
  level:
    com.tju.elm: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"