elm:
  db:
    host: xxx
    username: elm_app
    pw: "REDACTED_PASSWORD"
    slave:
      port: 3307
      username: elm_app
      pw: "REDACTED_PASSWORD"

  data:
    redis:
      host: xxx
      password:
      database: 2

  nacos:
    server-addr: xxx:8848
    username: nacos
    pw: 123456