server:
  port: 8888

spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${elm.db.host}:3306/elm_user
    username: ${elm.db.username}
    password: ${elm.db.pw}
    hikari: # 配置连接池读已提交
      transaction-isolation: TRANSACTION_READ_COMMITTED

  data:
    redis:
      host: ${elm.data.redis.host}
      port: 6379
      password: ${elm.data.redis.password}
      database: ${elm.data.redis.database}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

mybatis:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:com/tju/elm/user/mapper/*.xml

jwt:
  secret: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz123456
  token-validity-in-seconds: 86400
  token-validity-in-seconds-for-remember-me: 108000

logging:
  level:
    com.tju.elm: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

# swagger
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
