server:
  port: 8081

spring:
  application:
    name: elm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://REDACTED_IP:3306/elm
    username: elm_user
    password: zhijiage123
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

# swagger
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
