server:
  port: 8080

spring:
  application:
    name: elm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://REDACTED_IP:3306/elm_v2
    username: elm_v2
    password: zhijiage123

#  data:
#    redis:
#      host: REDACTED_IP
#      port: 6379
#      password: 123456
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

mybatis:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true


jwt:
  secret: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz123456
  token-validity-in-seconds: 86400
  token-validity-in-seconds-for-remember-me: 108000

# swagger
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
