spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${elm.db.host:REDACTED_IP}:3306/${elm.db.database}
    username: ${elm.db.username:root}
    password: ${elm.db.pw:Elm@2026Secure!}
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:${elm.mybatis.mp:/mapper/*.xml}