elm:
  db:
    host: 127.0.0.1
    username: root
    pw: 123456

  data:
    redis:
      host: 127.0.0.1
      password:
      database: 3

  rabbitmq:
    host: REDACTED_IP
    username: rabbit
    password: rabbit