elm:
  db:
    host: xxx
    username: xxx
    pw: xxx
    slave:
      port: 3307
      username: xxx
      pw: xxx

  data:
    redis:
      host: xxx
      password:
      database: 3

  rabbitmq:
    host: xxx
    username: rabbit
    password: rabbit

  nacos:
    server-addr: xxx:8848
    username: nacos
    pw: 123456