server:
  port: 8884

txcos:
  secretId: xxx
  secretKey: xxx
  region: ap-beijing
  bucketName: xxx
  enableAccelerate: true

# DeepSeek AI配置
deepseek:
  api-key: xxx

elm:
  db:
    database: elm_notification