elm:
  db:
    host: REDACTED_IP
    username: elm_app
    pw: "REDACTED_PASSWORD"
    slave:
      port: 3307
      username: elm_app
      pw: "REDACTED_PASSWORD"

  nacos:
    server-addr: REDACTED_IP:8848
    username: nacos
    pw: 123456